# BattleBox Configuration

# Game Settings
game:
  round-time: 180 # Time in seconds (3 minutes)
  min-players: 2
  max-players: 16
  countdown-time: 30

# Arena Settings
arena:
  default-block: WOOL # Block type for center objective
  center-size: 3 # Size of the center objective area

# Team Settings
teams:
  min-team-size: 1
  max-team-size: 4
  allow-team-friendly-fire: false

# Points System
points:
  kill: 50
  win: 100
  tie: 25

# Kit Settings
kits:
  default:
    enabled: true
    items:
      - IRON_SWORD
      - BOW
      - ARROW:32
      - IRON_ARMOR
      
# Messages
messages:
  prefix: "&8[&bBattleBox&8]"
  game-start: "&aThe game has started!"
  game-end: "&eGame Over!"
  round-start: "&aRound %round% has started!"
  round-end: "&eRound %round% has ended!"