name: BattleBox
version: '1.0-SNAPSHOT'
main: com.yourname.battlebox.BattleBox
api-version: '1.21'
authors: [YourName]
description: A BattleBox minigame plugin inspired by MCC
commands:
  battlebox:
    description: Main command for BattleBox plugin
    aliases: [bb]
    usage: /<command> [subcommand]